export const mimeFiles = {
    jpg: ['image/jpeg', 'image/pjpeg'],
    jpeg: ['image/jpeg', 'image/pjpeg'],
    gif: ['image/gif'],
    png: ['image/png'],
    bmp: ['image/bmp', 'image/x-windows-bmp'],
    doc: ['application/msword'],
    docx: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    odt: ['application/vnd.oasis.opendocument.text'],
    pdf: ['application/pdf'],
    xls: ['application/excel', 'application/vnd.ms-excel', 'application/x-excel', 'application/x-msexcel'],
    xlsx: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    txt: ['text/plain'],
    ppt: ['application/vnd.ms-powerpoint'],
    pptx: ['application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    csv: ['text/csv'],
    ods: ['application/vnd.oasis.opendocument.spreadsheet'],
    rtf: ['application/rtf'],
    tex: ['application/x-tex'],
    wpd: ['application/vnd.wordperfect'],
};
